name: 🐞 Bug report

description: Report a bug about pinos-ui

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: I am doing ... What I expect is ... What actually happening is ...
    validations:
      required: true

  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a link that can reproduce the problem you ran init.
      placeholder: Reproduction URL
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Please provide any reproduction steps that may need to be described.
      placeholder: Run `npm install` followed by `npm run dev`

  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --npmPackages '{pinos-ui,@pinos-ui/*}' --binaries --browsers`
      render: shell
      placeholder: System, Binaries, Browsers

  - type: dropdown
    id: package-manager
    attributes:
      label: Used Package Manager
      description: Select the used package manager
      options:
        - npm
        - yarn
        - pnpm
    validations:
      required: true
