export * from './components/button'
export * from './components/config-provider'
export * from './directives/ellipsis'
export { install } from './install-all'
export type { PropsOptions } from './props'
